function spec=xk2sptm(xk);
%XK2SPTM spec=xk2sptm(xk);
%   xk is 4D array:
%      frequency x taper x time x channel
%   spec is 3D array:
%      frequency x time x channel
%
%   spec=(log(mean(xk.*conj(xk),tapers))
%or
%   spec=log(mean(xk,2))

spec=squeeze( ...
              log( ...
                   mean( ...
                         xk.*conj(xk) ...
                     ,2) ...
                 ) ...
            );
